// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhreqihrktlgkardkwtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVocmVxaWhya3RsZ2thcmRrd3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzM5NTUsImV4cCI6MjA2MDEwOTk1NX0._on910Obdo3wC4KPbYo-o8JQpR4TPzDq4zEQuKqLW8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);